# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 5

    - name: Compile Test Verifiy and Checkstyle
      run: mvn clean compile test verify checkstyle:checkstyle

    - name: Build with Maven
      run: mvn -B spotbugs:spotbugs package --file pom.xml 