name: Manual production deploy

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'commit'
        required: false
      branch:
        description: 'branch'
        required: false
      tags:
        description: 'tag'
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Commit: $COMMIT"
          echo "Branch: $BRANCH"
          echo "Tags: $TAGS"
        env:
          COMMIT: ${{ github.event.inputs.commit }}
          BRANCH: ${{ github.event.inputs.branch }}
          TAGS: ${{ github.event.inputs.tags }}

  prod-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Clean Compile Test Verifiy and Checkstyle
        run: mvn clean compile test verify checkstyle:checkstyle

  prod-deploy:
    needs: prod-testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "production-floppa17"
          heroku_email: "nassima.addoun.1@ulaval.ca"
          healthcheck : "https://production-floppa17.herokuapp.com/health"
          delay: 90
          rollbackonhealthcheckfailed : true
